---

- name: Build a VM for compiling plan based scheduler linux kernel
  hosts: all
  become: true
  vars_files: ansible_vars.yml
  tasks:
    - name: install build dependencies
      apt:
        name: "{{ packages }}"
        state: latest

    - name: add custom ssh-key
      ansible.posix.authorized_key:
          user: vagrant
          state: present
          key: "{{ lookup('file', '/home/ml/.ssh/vm.pub') }}"

    - name: change default shell to zsh
      user:
          name: vagrant
          shell: /usr/bin/zsh

    - name: copy zshrc to remote
      copy:
          src: zshrc
          dest: /home/vagrant/.zshrc
          owner: vagrant
          group: vagrant


    - name: copy github ssh-key to remote
      copy:
          src: /home/ml/.ssh/github
          dest: /home/vagrant/.ssh
          owner: vagrant
          group: vagrant
          mode: '0111'

    - name: copy ssh-config for github
      copy:
          src: ssh_config
          dest: /home/vagrant/.ssh/config
          owner: vagrant
          group: vagrant

    - name: set timezone to Europe/Berlin
      timezone:
          name: Europe/Berlin

    # https://docs.ansible.com/ansible/2.3/parted_module.html
    - name: create partiton for new hdd
      parted:
          device: /dev/sdb
          number: 1
          state: present

    - name: make a filesystem for second hdd
      filesystem:
          fstype: ext4
          dev: /dev/sdb1

    - name: mount filesystem
      ansible.posix.mount:
          path: /home/vagrant/kernel_src
          src: /dev/sdb1
          fstype: ext4
          state: mounted

    - name: change ownership of kernel_src_local
      ansible.builtin.file:
          path: /home/vagrant/kernel_src
          state: directory
          recurse: yes
          owner: vagrant
          group: vagrant

    - name: create folder for plans
      file:
        path: /home/vagrant/kernel_src/plans
        state: directory
        mode: '0755'
        owner: vagrant


    - name: adding grub options to boot from last booted kernel
      blockinfile:
          path: /etc/default/grub
          block: |
            GRUB_SAVEDEFAULT=true
            GRUB_DEFAULT=saved
          backup: yes

    - name: updates grub after current changes
      command: update-grub
      become: yes

    - name: add export for nfs
      ansible.builtin.lineinfile:
          line: "/home/vagrant/kernel_src 192.168.1.2(rw,sync,no_subtree_check)"
          path: /etc/exports
          create: yes
      become: yes

    - name: copy tmux to remote
      copy:
          src: start_tmux_vm_sesh.sh
          dest: /home/vagrant/go_tmux.sh
          owner: vagrant
          group: vagrant
          mode: u+rwx

    - name: copy universal header files to source folder on remote
      copy:
          src: "{{ item }}"
          dest: /home/vagrant/kernel_src/master_thesis_linux/kernel/sched
          owner: vagrant
          group: vagrant
          force: yes
      with_items:
           - /home/ml/Dropbox/Master-Arbeit/code/level2/config.h
           - /home/ml/Dropbox/Master-Arbeit/code/level2/pbs_entities.h



           #- name: install oh-my-zsh
           # shell: /bin/bash -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# cp -v /boot/config-$(uname -r) .config

# compilen: get repo, git checkout pb, copy that to vm, cd src/pbs/ && cp -v /boot/config-$(uname -r) .config, change distcc to gcc in Makefile, make menuconfig, make, sudo make modules_install, sudo make install,
